import { useMemo, useState } from 'react'
import './App.css'

type View = 'overview' | 'sheet' | 'rituals' | 'table'
type Ritual = { name: string; circle: string; element: string; description: string; color: string }
const initialRituals: Ritual[] = [
  { name: 'Ouvir os sussurros', circle: '1º círculo', element: 'Conhecimento', description: 'Você toca uma superfície e escuta os últimos sons deixados nela.', color: 'gold' },
  { name: 'Amaldiçoar arma', circle: '2º círculo', element: 'Morte', description: 'A matéria ao redor da arma se corrompe, causando dano adicional.', color: 'purple' },
  { name: 'Cinerária', circle: '2º círculo', element: 'Energia', description: 'Uma nuvem de cinzas ocupa o espaço e esconde seus aliados.', color: 'blue' },
  { name: 'Paralisia', circle: '3º círculo', element: 'Sangue', description: 'O alvo sente seus músculos travarem sob uma ordem impossível.', color: 'red' },
]

function App() {
  const [view, setView] = useState<View>('overview')
  const [rituals, setRituals] = useState(initialRituals)
  const [search, setSearch] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [selectedToken, setSelectedToken] = useState('Evelyn')
  const [roll, setRoll] = useState<number | null>(null)
  const [newRitual, setNewRitual] = useState({ name: '', circle: '1º círculo', element: 'Conhecimento', description: '' })
  const filteredRituals = useMemo(() => rituals.filter((ritual) => ritual.name.toLowerCase().includes(search.toLowerCase()) || ritual.element.toLowerCase().includes(search.toLowerCase())), [rituals, search])
  const navigation: { id: View; label: string; icon: string }[] = [
    { id: 'overview', label: 'Santuário', icon: '⌂' }, { id: 'sheet', label: 'Minha ficha', icon: '◈' },
    { id: 'rituals', label: 'Rituais', icon: '✦' }, { id: 'table', label: 'Mesa virtual', icon: '▦' },
  ]
  function addRitual(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!newRitual.name.trim()) return
    setRituals((current) => [...current, { ...newRitual, color: 'gold' }])
    setNewRitual({ name: '', circle: '1º círculo', element: 'Conhecimento', description: '' })
    setShowModal(false)
  }

  return (
    <div className="app-shell">
      <aside className="sidebar"><div className="brand"><span className="brand-mark">☽</span><span>Toca do<br /><strong>Coelho</strong></span></div><div className="creator-stamp" aria-label="Carimbo de Julio Thiago Colares de Lima"><div className="stamp-ring"><span className="stamp-top">JULIO THIAGO COLARES DE LIMA</span><strong>{'{ }'}</strong><span className="stamp-icons">✦ · ⚄ · ✦</span><small>DEDICAÇÃO · CONHECIMENTO · HONESTIDADE</small></div></div><div className="campaign"><span className="eyebrow">CAMPANHA ATIVA</span><strong>O véu entre nós</strong><span>Força Umbra · 4 jogadores</span></div><nav>{navigation.map((item) => <button key={item.id} className={view === item.id ? 'active' : ''} onClick={() => setView(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><button className="admin-link" onClick={() => setView('rituals')}><span>⚙</span> Painel do mestre</button><div className="user-chip"><div className="avatar">EC</div><div><strong>Evelyn Croft</strong><small>Investigadora</small></div><span>•••</span></div></div></aside>
      <main className="main-content"><header className="topbar"><div className="breadcrumbs">CAMPANHA <span>/</span> <strong>{navigation.find((item) => item.id === view)?.label.toUpperCase()}</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notificações">♧<i /></button><button className="invite-button" onClick={() => setView('table')}>＋ Convidar jogador</button></div></header>
        {view === 'overview' && <section className="page"><div className="page-heading"><div><span className="eyebrow">DOMINGO, 20 DE SETEMBRO</span><h1>Bem-vindo de volta, Evelyn<span className="gold">.</span></h1><p>O que vamos descobrir hoje?</p></div><button className="primary-button" onClick={() => setView('table')}>Entrar na mesa <span>→</span></button></div><div className="hero-banner"><div><span className="eyebrow gold-text">PRÓXIMA SESSÃO · EM 2 DIAS</span><h2>O chamado da<br /><em>floresta negra</em></h2><p>Capítulo III · A casa onde o silêncio mora</p><button className="banner-button" onClick={() => setView('table')}>Abrir mesa virtual <span>↗</span></button></div><div className="moon-art"><span>☽</span><i>✦</i><b>✧</b></div></div><div className="section-title"><div><span className="eyebrow">ACESSO RÁPIDO</span><h2>Seu santuário</h2></div><button className="text-button" onClick={() => setView('sheet')}>Ver minha ficha →</button></div><div className="quick-grid"><button className="quick-card ritual-card" onClick={() => setView('rituals')}><span className="card-icon">✦</span><span><strong>Biblioteca de rituais</strong><small>{rituals.length} rituais disponíveis para estudar</small></span><b>→</b></button><button className="quick-card map-card" onClick={() => setView('table')}><span className="card-icon">▦</span><span><strong>Mapa da sessão</strong><small>Ruínas de Santa Dália · 4 jogadores online</small></span><b>→</b></button></div><div className="lower-grid"><div className="panel activity"><div className="panel-heading"><div><span className="eyebrow">DIÁRIO DA CAMPANHA</span><h2>Atividade recente</h2></div><button className="text-button">Ver tudo</button></div><div className="activity-row"><span className="activity-dot purple">✦</span><div><strong>O mestre adicionou um novo ritual</strong><small>Paralisia · há 18 minutos</small></div><span>···</span></div><div className="activity-row"><span className="activity-dot gold">▦</span><div><strong>Mapa atualizado na mesa virtual</strong><small>Ruínas de Santa Dália · ontem</small></div><span>···</span></div></div><div className="panel quote"><span className="quote-mark">“</span><p>O medo não está no que se esconde na escuridão, mas no que a escuridão revela sobre nós.</p><small>— Diário do Professor Carvalho</small></div></div></section>}
        {view === 'sheet' && <section className="page"><div className="page-heading compact"><div><span className="eyebrow">FICHA DE PERSONAGEM</span><h1>Evelyn Hp Croft<span className="gold">.</span></h1><p>Uma investigadora que aprendeu a ouvir o que não foi dito.</p></div><button className="primary-button">Editar ficha <span>✎</span></button></div><div className="character-grid"><div className="character-portrait"><div className="portrait-symbol">EC</div><span>INVESTIGADORA</span><strong>NEX 35%</strong></div><div className="panel stats-panel"><div className="stat-header"><span><small>JOGADOR</small><strong>julio</strong></span><span><small>ORIGEM</small><strong>Investigador</strong></span><span><small>CLASSE</small><strong>Especialista</strong></span></div><div className="stat-bars"><div><label>VIDA <b>32 / 32</b></label><i><em className="health" style={{ width: '88%' }} /></i></div><div><label>ESFORÇO <b>28 / 28</b></label><i><em className="effort" style={{ width: '72%' }} /></i></div><div><label>SANIDADE <b>42 / 50</b></label><i><em className="sanity" style={{ width: '84%' }} /></i></div></div><div className="attributes"><div><b>FOR</b><strong>2</strong></div><div><b>AGI</b><strong>3</strong></div><div><b>INT</b><strong>4</strong></div><div><b>PRE</b><strong>2</strong></div><div><b>VIG</b><strong>3</strong></div></div></div></div><div className="section-title"><div><span className="eyebrow">INVENTÁRIO MÍSTICO</span><h2>Seus rituais preparados</h2></div><button className="text-button" onClick={() => setView('rituals')}>Ver biblioteca →</button></div><div className="ritual-list">{rituals.slice(0, 3).map((ritual) => <RitualItem key={ritual.name} ritual={ritual} />)}</div></section>}
        {view === 'rituals' && <section className="page"><div className="page-heading compact"><div><span className="eyebrow">CONHECIMENTO ARCANO</span><h1>Biblioteca de rituais<span className="gold">.</span></h1><p>Registre, organize e compartilhe o conhecimento da campanha.</p></div><button className="primary-button" onClick={() => setShowModal(true)}>＋ Novo ritual</button></div><div className="library-toolbar"><div className="search-box">⌕<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nome ou elemento..." /></div><button className="filter-button">Todos os círculos <span>⌄</span></button><span className="result-count">{filteredRituals.length} rituais</span></div><div className="ritual-list full-list">{filteredRituals.map((ritual) => <RitualItem key={ritual.name} ritual={ritual} />)}</div></section>}
        {view === 'table' && <section className="page table-page"><div className="page-heading compact"><div><span className="eyebrow">MESA VIRTUAL · AO VIVO</span><h1>Ruínas de Santa Dália<span className="gold">.</span></h1><p>Mapa compartilhado · 4 jogadores conectados</p></div><div className="online-list"><span className="online-dot" /> 4 online <button className="primary-button small" onClick={() => setRoll(Math.floor(Math.random() * 20) + 1)}>Rolar d20</button></div></div><div className="table-layout"><div className="map-wrap"><div className="map-toolbar"><span>☷ <strong>Ruínas de Santa Dália</strong></span><span><button>−</button><b>100%</b><button>＋</button></span><span><button>↗</button> Tela cheia</span></div><div className="map-grid"><div className="map-room room-one"><span>Entrada</span></div><div className="map-room room-two"><span>Santuário</span></div><div className="map-room room-three"><span>Biblioteca</span></div><button className={`token token-evelyn ${selectedToken === 'Evelyn' ? 'selected' : ''}`} onClick={() => setSelectedToken('Evelyn')}><span>EC</span><small>Evelyn</small></button><button className={`token token-npc ${selectedToken === 'Aparição' ? 'selected' : ''}`} onClick={() => setSelectedToken('Aparição')}><span>?</span><small>Aparição</small></button><button className="token token-friend"><span>LM</span><small>Lívia</small></button></div><div className="map-footer"><span>▣ Ferramentas</span><span>◉ Grade ativada</span><span className="selected-label">Selecionado: <strong>{selectedToken}</strong></span></div></div><aside className="table-side"><div className="panel chat-panel"><div className="panel-heading"><h2>Registro da mesa</h2><span className="live-badge">AO VIVO</span></div><div className="chat-message"><div className="mini-avatar gold-bg">MC</div><p><strong>Mestre Carvalho</strong><span>Abre a porta devagar...</span><small>20:41</small></p></div><div className="chat-message"><div className="mini-avatar purple-bg">EC</div><p><strong>Você</strong><span>Eu lanço Ouvir os sussurros.</span><small>20:42</small></p></div>{roll && <div className="roll-result"><span>✦</span> Evelyn rolou <strong>d20: {roll}</strong></div>}<div className="chat-input">Diga algo... <span>↗</span></div></div><div className="panel players-panel"><div className="panel-heading"><h2>Jogadores</h2><span>4 / 6</span></div><div className="player-line"><span className="mini-avatar purple-bg">EC</span><strong>Evelyn Croft<small>Você · Investigadora</small></strong><i className="mic">◉</i></div><div className="player-line"><span className="mini-avatar blue-bg">LM</span><strong>Lívia Mendes<small>Especialista</small></strong><i className="mic">◉</i></div><div className="player-line"><span className="mini-avatar gold-bg">MC</span><strong>Mestre Carvalho<small>Mestre</small></strong><i className="mic">◉</i></div></div></aside></div></section>}
      </main>
      {showModal && <div className="modal-backdrop" onMouseDown={() => setShowModal(false)}><form className="modal" onSubmit={addRitual} onMouseDown={(event) => event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow gold-text">PAINEL DO MESTRE</span><h2>Novo ritual</h2></div><button type="button" className="close-button" onClick={() => setShowModal(false)}>×</button></div><label>Nome do ritual<input autoFocus required value={newRitual.name} onChange={(event) => setNewRitual({ ...newRitual, name: event.target.value })} placeholder="Ex: Revelar o oculto" /></label><div className="form-row"><label>Círculo<select value={newRitual.circle} onChange={(event) => setNewRitual({ ...newRitual, circle: event.target.value })}><option>1º círculo</option><option>2º círculo</option><option>3º círculo</option><option>4º círculo</option></select></label><label>Elemento<select value={newRitual.element} onChange={(event) => setNewRitual({ ...newRitual, element: event.target.value })}><option>Conhecimento</option><option>Energia</option><option>Morte</option><option>Sangue</option></select></label></div><label>Descrição<textarea value={newRitual.description} onChange={(event) => setNewRitual({ ...newRitual, description: event.target.value })} placeholder="Descreva os efeitos deste ritual..." /></label><button className="primary-button modal-submit">Salvar ritual <span>→</span></button></form></div>}
    </div>
  )
}

function RitualItem({ ritual }: { ritual: Ritual }) {
  return <article className="ritual-item"><span className={`ritual-glyph ${ritual.color}`}>✦</span><div className="ritual-copy"><div><h3>{ritual.name}</h3><span className="tag">{ritual.circle}</span><span className="element">{ritual.element}</span></div><p>{ritual.description}</p></div><button className="more-button" aria-label={`Abrir ${ritual.name}`}>↗</button></article>
}

export default App
